# Generated by Django 5.1.4 on 2024-12-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnings', '0004_topic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
