# Generated by Django 5.1.4 on 2024-12-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnings', '0005_rename_owner_topic_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
